---
title: "1B ANNOVA FOR PLANTH GROWTH DATASET"
author: "Gonzales Dwight Jiro M."
output: github_document
---

## Load Necessary Libraries

```{r setup, echo=TRUE, warning=FALSE, message=FALSE}
library(tidyverse)                    
library(tidyr)                       
library(rstatix)                      
library(ggplot2)                      
library(ggpubr)                       
library(emmeans)                       
library(faraway) 
library(ggbeeswarm)
library(ggdist)
library(tidyquant)
library(ggthemes)

PlantGrowth %>%
  ggplot(aes(x = group, y = weight, fill = group)) +
  
  stat_halfeye(
    adjust = 0.5,               
    justification = -0.2,       
    .width = 0,                 
    point_colour = NA           
  ) +
  
  geom_boxplot(
    width = 0.12, 
    outlier.color = NA,         
    alpha = 0.5                 
  ) +
  
  stat_dots(
    side = "left",              
    justification = 1.1,        
    binwidth = 0.25,           
    size = 1.5                  
  ) +
  
  theme_minimal() +
  labs(title = "Raincloud Plot for Plant Growth by Group",
       x = "Group", 
       y = "Weight") +
  theme(legend.position = "none")  


PlantGrowth %>%
  group_by(group) %>%
  summarize(
    count = n(),
    mean = mean(weight, na.rm = TRUE),
    sd = sd(weight, na.rm = TRUE),
    median = median(weight, na.rm = TRUE),
    min = min(weight, na.rm = TRUE),
    max = max(weight, na.rm = TRUE),
    shapiro_p_value = shapiro_test(weight)$p.value
  )


PlantGrowth %>%
  levene_test(weight ~ group)


res.aov <- PlantGrowth %>% anova_test(weight ~ group)
res.aov

weight_aov = aov(weight ~ group, data = PlantGrowth)
summary(weight_aov)


pwc <- PlantGrowth %>% tukey_hsd(weight ~ group)
pwc

# Tukey's HSD post hoc test
tukey_result <- TukeyHSD(weight_aov)

print(tukey_result)

plot(TukeyHSD(weight_aov, conf.level = 0.95))




