---
title: "2 WAY ANNOVA"
author: "GONZALES_QUINTEROS"
output: github_document
---

```{r setup, echo=TRUE, warning=FALSE, message=FALSE}
library(palmerpenguins)
library(dplyr)
library(tidyverse)                    
library(tidyr)                       
library(rstatix)                      
library(ggplot2)                      
library(ggpubr)                       
library(emmeans)                       
library(faraway) 
library(ggbeeswarm)
library(ggdist)
library(tidyquant)
library(ggthemes)
library(car)

data <- read.csv("C:\\Users\\DWIGHT JIRO\\Downloads\\Political Interest.csv")
head(data)


data %>%
  group_by(gender, education_level) %>%
  summarize(
    count = n(),
    mean = mean(political_interest, na.rm = TRUE),
    sd = sd(political_interest, na.rm = TRUE),
    median = median(political_interest, na.rm = TRUE),
    min = min(political_interest, na.rm = TRUE),
    max = max(political_interest, na.rm = TRUE),
    shapiro_p_value = shapiro_test(political_interest)$p.value
  )


data$gender <- as.factor(data$gender)
data$education_level <- as.factor(data$education_level)

# Levene's test for homogeneity of variances
leveneTest(political_interest ~ gender * education_level, data = data)


data$gender <- as.factor(data$gender)
data$education_level <- as.factor(data$education_level)
data$group <- interaction(data$gender, data$education_level, sep = "_")

# Raincloud plot
data %>%
  ggplot(aes(x = group, y = political_interest, fill = group)) +
  
  stat_halfeye(
    adjust = 0.5,               
    justification = -0.2,       
    .width = 0,                 
    point_colour = NA           
  ) +
  
  geom_boxplot(
    width = 0.12, 
    outlier.color = NA,         
    alpha = 0.5                 
  ) +
  
  stat_dots(
    side = "left",              
    justification = 1.1,        
    binwidth = 1,               
    size = 1.5                  
  ) +
  
  theme_minimal() +
  labs(title = "Raincloud Plot for Political Interest by Gender and Education Level",
       x = "Group (Gender_Education Level)", 
       y = "Political Interest") +
  theme(legend.position = "none")


anova_model <- aov(political_interest ~ gender * education_level, data = data)
summary(anova_model)


# Tukey HSD test
tukey_result <- TukeyHSD(anova_model, conf.level = 0.95)

print(tukey_result)
plot(tukey_result)




par(mar = c(4, 4, 2, 1))  
interaction.plot(
  x.factor = data$education_level, 
  trace.factor = data$gender, 
  response = data$political_interest,
  col = c("blue", "red"),  # Colors for the lines representing different genders
  lty = 1,  # Line type for the plot (solid lines)
  type = "b",  # Both points and lines will be plotted
  xlab = "Education Level",  # Label for the x-axis
  ylab = "Political Interest",  # Label for the y-axis
  legend = TRUE,  # Show legend
  trace.label = "Gender",  # Label for the legend
  main = "Interaction Plot: Education Level and Gender on Political Interest"  # Main title of the plot
)

text(x = 2.5, y = 50, 
     col = "black", 
     cex = 0.9,  
     pos = 4)  
grid()